export enum TaskEnum {
  CorreccionEstilosRotos = "Corrección de estilos",
  ReestructuracionVistas = "Reestructuración de vistas",
  ValidacionFormularios = "Validación de formularios",
  OrganizacionComponentes = "Organización",
  DocumentacionComponentes = "Documentación",
  CreacionEndpoints = "Creación de endpoints",
  OptimizacionNavegacion = "Optimización",
  CreacionNuevasRutas = "Creación de nuevas rutas",
  ImplementacionComponentes = "Creación de componentes",
  ImplementacionHooks = "Creación de hooks",
  ImplementacionI18n = "Implementación de i18n",
  ImplementacionPruebasUnitarias = "Implementación de testing",
  ImplementacionTablas = "Creacion de tablas",
  CRUDsAxios = "CRUDs",
}
